version: "3.8"

services:
    instascrapper:
        build: .
        ports:
            - "8080:8080"
        depends_on:
          - postgre
        environment:
          - DB_PORT=5432
          - DB_USER=postgres
          - DB_PASSWORD=postgres
          - DB_NAME=postgres
          - DB_HOST=postgre

    postgre:
      image: postgres:13.2-alpine
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "postgres"
